src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Total_Number_of_Districts__c</fullName>
        <label>Total Number of Districts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_States__c</fullName>
        <label>Total Number of States</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Districts</relationshipLabel>
        <relationshipName>Districts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Districts__c</fullName>
        <label>Total Number of Districts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AggregrateQueries.cls
public with sharing class AggregrateQueries {
    //Do Aggregrate Queries For finding State and District From Country
    public AggregrateQueries() {
        try
        {
        Map<ID,Country__c> mapOfIdForCountry = new Map<ID,Country__c>();
        //In this we can do aggregrate Queries for finding Total Number Of States from Country
        for (AggregateResult state : [Select Country__c, COUNT(Name) Total_Number_Of_States from State__c Group By Country__c]) 
        {
            Country__c cont = new Country__c();
            cont.ID = (ID)state.get('Country__c');
            cont.Total_Number_Of_States__c = (Decimal)state.get('Total_Number_Of_States');
            mapOfIdForCountry.put(cont.ID,cont);
        }
        if(mapOfIdForCountry != null) {
        update mapOfIdForCountry.values();
        }
        }
        catch (DmlException e)
        {
            system.debug('An unexpected error has occurred: ' + e.getMessage());
        }

        try
        {
        Map<ID,State__c> mapIdForState = new Map<ID,State__c>();
        //In this we can do Aggregate Queries for finding Total Number Of District from State
        for (AggregateResult district : [Select State__c, COUNT(Name) Total_Number_Of_Districts from District__c Group By State__c]) 
        {
            State__c stat = new State__c();
            stat.ID = (ID)district.get('Country__c');
            stat.Total_Number_of_Districts__c = (Decimal)district.get('Total_Number_Of_Districts');
            mapIdForState.put(stat.ID,stat);
        }
        if(mapIdForState != null) {
        update mapIdForState.values();
        }
        }
        catch (DmlException e)
        {
            system.debug('An unexpected error has occurred: ' + e.getMessage());
        }

        try
        {
        Map<ID,Country__c> mapOfCountryWithDistrict = new Map<ID,Country__c>();
        // In this we can do Aggregrate Queries for finding Total Number Of District from Country
        for (AggregateResult countryList : [Select Country__c, sum(Total_Number_Of_Districts__c) Total_Number_Of_Districts fROM State__c Group By Country__c]) 
        {
            Country__c cont = new Country__c();
            cont.ID = (ID)countryList.get('Country__c');
            cont.Total_Number_of_Districts__c = (Decimal)countryList.get('Total_Number_Of_Districts');
            mapOfCountryWithDistrict.put(cont.ID,cont);
        }
        if(mapOfCountryWithDistrict != null) {
        update mapOfCountryWithDistrict.values();
        }
        }
        catch (DmlException e)
        {
            system.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }
}